name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print Full Ref
        run: 'echo "Ref: ${{ github.ref }}"'

      - name: Print Branch Name
        run: 'echo "Branch: ${{ github.ref_name }}"'

      - name: Print PR Source Branch
        if: github.event_name == 'pull_request'
        run: 'echo "Source Branch: ${{ github.head_ref }}"'
